# name: Deploy to Heroku
# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Login to Heroku
#         run: git push heroku ${{ github.ref }}:refs/heads/main --force 
#         uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
#         with:
#           heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#           heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#           heroku_email: "masya868686@gmail.com"
name: Deploy to Heroku
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Heroku
        run: |
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          git fetch heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Push to Heroku
        run: git push heroku ${{ github.ref_name }}:refs/heads/main --force
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: "masya868686@gmail.com"
          usedocker: false
          branch: main
